### ISSUE TITLE
Deprecation Error

### ISSUE THREAD

**Issue by epaaso** [ToryDeng/scGeneClust#2]
When installing GeneClust in python 3.11,  there is a deprecation warning.
It says that sklearn is deprecated and is part of scikit-learn.

Using this flag SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
installs correctly, but it would be best to remove it from the requirements.

**Comment by ToryDeng** [comment]
Hello epaaso,

I have deleted it in both the setup.py and requirements.txt. Thank you for your advice.

**Comment by ToryDeng** [comment]
Hello @epaaso,

I've removed it from both the setup.py and requirements.txt. Thank you for your advice.

**Comment by ToryDeng** [comment]
I'll close this issue if you don't have any other comments.
